"""
Django settings for recommenderbackend project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment variables
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# Dedicated JWT signing key (backend/jwt.py). Kept separate from SECRET_KEY so
# the frontend middleware can verify token signatures without holding the key
# behind password-reset/email-change links and Django sessions. Empty falls
# back to SECRET_KEY (dev/CI without a .env keep working, unsigned-edge mode).
JWT_SIGNING_KEY = env('JWT_SIGNING_KEY', default='')

# AWS S3 (company photo uploads)
AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY')
AWS_S3_REGION_NAME = env('AWS_S3_REGION_NAME')
AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME')
AWS_S3_UPLOADS_ROOT = env('AWS_S3_UPLOADS_ROOT', default='uploads')
AWS_S3_MAX_UPLOAD_SIZE_BYTES = 5 * 1024 * 1024
AWS_S3_ALLOWED_CONTENT_TYPES = ['image/jpeg', 'image/jpg', 'image/png', 'image/webp']

# Email (password reset / email verification)
# Defaults to printing emails to the console so local dev needs no extra setup.
# Set EMAIL_BACKEND=django_ses.SESBackend in .env to send real emails via SES,
# reusing the AWS credentials above.
EMAIL_BACKEND = env('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
AWS_SES_REGION_NAME = env('AWS_SES_REGION_NAME', default=AWS_S3_REGION_NAME)
AWS_SES_REGION_ENDPOINT = f'email.{AWS_SES_REGION_NAME}.amazonaws.com'
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='Recommender <noreply@recapp.example>')

# Base URL of the frontend, used to build links inside emails
# (verify-email, password reset, and the /candidate/messages/<id> link in
# new-message notifications).
FRONTEND_URL = env('FRONTEND_URL', default='http://localhost:3000')

# Lifetime of password-reset and email-change links (both use Django's
# PasswordResetTokenGenerator, which reads this setting). Email VERIFICATION
# links keep their own 3-day window - see tokens.EmailVerificationTokenGenerator.
PASSWORD_RESET_TIMEOUT = 3600

# Public name of the product, used in email subjects/bodies and the email
# template's wordmark. Change it in .env to rebrand every email at once.
WEBSITE_NAME = env('WEBSITE_NAME', default='Recommender App')

# SECURITY WARNING: don't run with debug turned on in production!
# Env-driven for production (DEBUG=False + real hosts in .env); the defaults
# keep local dev zero-config.
DEBUG = env.bool('DEBUG', default=True)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "backend",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Secure by default: a view without an explicit @permission_classes needs a
    # token. The handful of public views (register, password reset, email
    # verification) declare AllowAny themselves; tests.py sweeps urlpatterns to
    # prove nothing else slips through.
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'password_reset': '5/hour',
        'email_verify': '5/hour',
        # Message sends only (PostScopedRateThrottle skips reads): spam guard
        # sized well above any human typing speed.
        'messages': '30/min',
        # Application submissions only (creates are idempotent, so retries are
        # cheap); GET list/polling is never throttled.
        'applications': '20/hour',
        # Credential endpoints (token_views.py): failed logins count, per IP
        # for anonymous callers. Refresh is sized well above the middleware's
        # one-exchange-per-access-lifetime cadence.
        'login': '10/min',
        'token_refresh': '60/min',
    },
}

from datetime import timedelta

SIMPLE_JWT = {
    # Env-driven so production can run short-lived tokens (the middleware
    # refreshes silently, and each refresh re-stamps the role claim from the
    # DB - see token_views.py - so a short lifetime also bounds how long a
    # stale claim can live). 60 is the documented production value; the long
    # dev default keeps local sessions painless.
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=env.int('JWT_ACCESS_MINUTES', default=900)),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=10),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,

    "ALGORITHM": "HS256",
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,

    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",

    # Dual-verify token classes (backend/jwt.py): sign with JWT_SIGNING_KEY,
    # verify with it first and the legacy SECRET_KEY during rotation.
    "AUTH_TOKEN_CLASSES": ("backend.jwt.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",

    "JTI_CLAIM": "jti",

    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),

    "TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
    # Re-stamps the role claim from the DB on every refresh (default copies
    # claims verbatim) - pre-claim sessions self-heal, role edits propagate.
    "TOKEN_REFRESH_SERIALIZER": "backend.token_views.RoleStampingTokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER": "rest_framework_simplejwt.serializers.TokenVerifySerializer",
    "TOKEN_BLACKLIST_SERIALIZER": "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",
    "SLIDING_TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer",
    "SLIDING_TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSlidingSerializer",
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        # SQLITE_PATH lets the e2e suite run against a throwaway database.
        "NAME": env('SQLITE_PATH', default=str(BASE_DIR / "db.sqlite3")),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Tell Django that we are using the new custom User model
AUTH_USER_MODEL = 'backend.MyUser'
# Structured console logging. backend.roles emits `role_denied` warnings when
# an authenticated token is refused for being on the wrong side of the
# marketplace - the audit trail for the role separation.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'console': {'format': '{levelname} {asctime} {name} {message}', 'style': '{'},
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'console'},
    },
    'root': {'handlers': ['console'], 'level': 'INFO'},
}
